#!/bin/bash
cd ~/pw/core
python pwb.py masti/ms-featured.py -page:"Kategoria:Artykuły na medal" -outpage:"Wikipedia:Brakujące artykuły na medal z innych Wikipedii" -summary:"Bot aktualizuje listę" -test
python pwb.py masti/ms-featured.py -page:"Kategoria:Dobre artykuły" -good -outpage:"Wikipedia:Brakujące dobre artykuły z innych Wikipedii" -summary:"Bot aktualizuje listę" -test
python pwb.py masti/ms-featured.py -page:"Kategoria:Listy na medal" -lists -outpage:"Wikipedia:Brakujące listy na medal z innych Wikipedii" -summary:"Bot aktualizuje listę" -test

